### ISSUE TITLE
ZSS address space - S0C4  RSN=00000011

### ISSUE THREAD

**Issue by gatogatogato** [zowe/zss#122]
I'm not sure if this is the right place to report this but I am currently trying to get ZOWE running but right after the startup of the ZSS address space starts I see these messages and then it crashes:
```
MSGID     MSGTEXT
ZWES0001I ZSS Cross-Memory Server starting, version is 1.0.5
ZWES0002I Input parameters at 0x6FE6:
ZWES0101I 00000000  0016D5C1 D4C57EE9 E6C5E2C9 E26DE2E3 |..NAME=ZWESIS_ST|
```
The dump is a SYSTEM COMPLETION CODE=0C4  REASON CODE=00000011

**Comment by ifakhrutdinov** [comment]
@gatogatogato are those the only messages you have in the log? Have you captured a dump?

**Comment by gatogatogato** [comment]
@ifakhrutdinov These are all messages in the log indeed. I did capture a SYSMDUMP.

**Comment by ifakhrutdinov** [comment]
@gatogatogato Can you please share your ZWESIS STC JCL content?

**Comment by gatogatogato** [comment]
@ifakhrutdinov It looks like this (comments excluded for readability)
```
//ZWESIS01  PROC NAME='ZWESIS_STD',MEM=00,RGN=0M
//ZWESIS01 EXEC PGM=ZWESIS01,REGION=&RGN,
//         PARM='NAME=&NAME,MEM=&MEM'
//STEPLIB  DD   DSNAME=XXXX.ZOWE.LOADLIB,DISP=SHR
//PARMLIB  DD   DSNAME=XXXX.ZOWE.PARMLIB,DISP=SHR
//SYSPRINT DD   SYSOUT=M
//SYSMDUMP DD   SYSOUT=M
```
The LOADLIB is APF authorized and contains the load module ZWESIS01
The STC is named ZOWESIS and runs as user ZOWESIS.

**Comment by ifakhrutdinov** [comment]
Thanks, this looks good.

If possible, can you copy-paste info about the registers, PSW, etc at the time of the ABEND?

And if you can capture an SVC dump, that'd be even better. Not sure how it'd be transferred but we could probably extract some info from IPCS.

**Comment by gatogatogato** [comment]
Dump info below: 
```
IEA995I SYMPTOM DUMP OUTPUT
SYSTEM COMPLETION CODE=0C4  REASON CODE=00000011
 TIME=14.40.18  SEQ=24732  CPU=0000  ASID=0249
 PSW AT TIME OF ERROR  078D1001   9931597A  ILC 6  INTC 11
   ACTIVE MODULE           ADDRESS=00000000_19300000  OFFSET=0001597A
   NAME=ZWESIS01
   DATA AT PSW  19315974 - 00F1B914  00FFE3EF  E0000090
   AR/GR 0: 00000000/00000020   1: 00000000/0000000A
         2: 00000000/1937944A   3: 00000000/19315C28
         4: 00000000/19379440   5: 00000000/1947B5A0
         6: 00000000/007D5FC8   7: 00000000/00F26400
         8: 00000000/007EBF88   9: 00000000/007FEA08
         A: 00000000/00000000   B: 00000000/00000000
         C: 00000000/1947A948   D: 00000000/1937A5A0
         E: 00000000/00006FE6   F: 00000001/0000001A
 END OF SYMPTOM DUMP
IEF450I ZOWESIS ZOWESIS - ABEND=S0C4 U0000 REASON=00000011
        TIME=14.40.18
```
Thanks for the support!
I think we are not allowed to upload dumps on Github :(

**Comment by ifakhrutdinov** [comment]
According to the PSW it was running in key 8 (must be in key 4). Although it shouldn't have caused that S0C4, I think the key issue needs to be addressed first.

Have you added the required entries to PPT? You can check that using `D PPT,NAME=ZWES*` operator command. Please copy-paste the output here (it shouldn't contain any sensitive information).

**Comment by gatogatogato** [comment]
I have these entries in the SCHED00 parmlib member and we IPLed the system since first entered them.
PPT PGMNAME(ZWESIS01) KEY(4) NOSWAP
PPT PGMNAME(ZWESAUX)  KEY(4) NOSWAP
Also I dynamically activated those be using the SET SCH=00 command. The D PPT command shows this: 
```
IEF386I 14.58.55 DISPLAY PPT 838
PARMLIB VALUES MATCHING: ZWES*
PGMNAME  NC NS PR ST ND BP KEY 2P 1P NP NH CP DA PA
ZWESAUX   .  Y  .  .  .  .  4   .  .  .  .  .  .  .
ZWESIS01  .  Y  .  .  .  .  4   .  .  .  .  .  .  .
NO DEFAULT VALUES
REFERENCE
```

**Comment by ifakhrutdinov** [comment]
Okay, this looks correct.

Can you go to the load library datasets (`=3.4` in ISPF), open it with `V` and tell what value `ZWESIS01` has in the `AC` column? Or just attach the screenshot from there if possible.

**Comment by gatogatogato** [comment]
Does that work? 
![Screenshot](https://user-images.githubusercontent.com/737459/70628630-c786ef00-1c28-11ea-8acd-9a3e6eea77eb.png)

![Screenshot hex](https://user-images.githubusercontent.com/737459/70628721-f56c3380-1c28-11ea-9222-c8fd94cbce49.png)

**Comment by ifakhrutdinov** [comment]
Sorry, I meant the member view, not the actual content of the load module :)

![image](https://user-images.githubusercontent.com/34161978/70629043-9824b200-1c29-11ea-9623-4317cc855b57.png)

**Comment by gatogatogato** [comment]
No problem. Looks like this:
```

Command ===>                                                  Scroll ===> CSR
           Name     Prompt        Alias-of     Size      TTR     AC   AM   RM
_________ ZWESAUX                            0005F128   000005   01    64  ANY
_________ ZWESIS01 *Viewed                   00078E90   000004   01    64  ANY
```

**Comment by ifakhrutdinov** [comment]
Okay, then just to make sure, can please you issue `D PROG,APF,DSNAME=you-dataset-name` and paste the output?

Also, is the volume displayed in the output the same as you expect? If it shows `SMS`, is the PDSE dataset you use SMS-managed?

**Comment by gatogatogato** [comment]
D APF command output shows this: 
```
CSV450I 15.32.44 PROG,APF DISPLAY 920
FORMAT=DYNAMIC
ENTRY VOLUME DSNAME
   1  *SMS*  XXXX.ZOWE.LOADLIB
```
The dataset is SMS managed for sure.

**Comment by ifakhrutdinov** [comment]
I've been able to reproduce the ABEND by removing the module from PPT and running it in key 8, though I got the appropriate messages in SYSPRINT
```
DATESTAMP              JOBNAME  ASCB    (ASID) TCB       MSGID     MSGTEXT                                                         
2019/12/11-10:04:23.77 ZWESIS01 00FBA880(0065) 008F8588  ZWES0001I ZSS Cross-Memory Server starting, version is 1.0.5          
2019/12/11-10:04:23.77 ZWESIS01 00FBA880(0065) 008F8588  ZWES0002I Input parameters at 0x6FE6:                                     
2019/12/11-10:04:23.78 ZWESIS01 00FBA880(0065) 008F8588  ZWES0101I 00000000  0016D5C1 D4C57EE9 E6C5E2C9 E26DC9D9 |..NAME=ZWESIS_ST|
2019/12/11-10:04:23.78 ZWESIS01 00FBA880(0065) 008F8588  ZWES0101I 00000010  C66BD4C5 D47EF0F0 00000000 0000     |D,MEM=00......|  
2019/12/11-10:04:23.78 ZWESIS01 00FBA880(0065) 008F8588  ZWES0004I Server name is 'ZWESIS_STD      '                               
2019/12/11-10:04:23.78 ZWESIS01 00FBA880(0065) 008F8588  ZWES0118E Core server started in wrong key 8                              
2019/12/11-10:04:23.78 ZWESIS01 00FBA880(0065) 008F8588  ZWES0011E ZSS Cross-Memory server not started, RC = 55                    
2019/12/11-10:04:23.78 ZWESIS01 00FBA880(0065) 008F8588  ZWES0013E ZSS Cross-Memory Server terminated due to an error, status = 8  
```

Trying to figure out why ZWESIS01 would start in key 8 on your system...

**Comment by gadyck** [comment]
When the problem occurred did you get the following message in the joblog-
  IEF188I PROBLEM PROGRAM ATTRIBUTES ASSIGNED
If so, then there was a dataset APF authorization issue that prevented honoring the PPT entry.  If not, then the PPT entry was missing.

**Comment by gatogatogato** [comment]
@gadyck I did not get the `IEF188I` but as you can see above I checked for the correct PPT entries (see https://github.com/zowe/zss/issues/122#issuecomment-564554790). 
I'm not sure if the dataset must be APF authorized at IPL but as I am in a testing phase for ZOWE I'd rather set the APF authorization dynamically.

**Comment by ifakhrutdinov** [comment]
@gatogatogato dynamic APF-authorization should be ok.

**Comment by ifakhrutdinov** [comment]
@gatogatogato can you please check if the ZWESIS01 module is (for some reason) in LPA?

`D PROG,LPA,MODNAME=ZWESIS01`

**Comment by ifakhrutdinov** [comment]
We can also make sure that the correct `ZWESIS01` gets loaded. If you rename it to `ZWESIS02` you should get an S806 ABEND.

**Comment by ifakhrutdinov** [comment]
@gatogatogato also, if possible, can you include

* *all* STC output?
* Do `I` in front of the load library (`XXXX.ZOWE.LOADLIB`) in ISPF and show the results

Thanks

**Comment by gatogatogato** [comment]
It's not in LPA:
```
D PROG,LPA,MODNAME=ZWESIS01
 CSV550I 13.52.59 LPA DISPLAY 795
   ZWESIS01 WAS NOT FOUND IN THE LPA
```

S806 occurs when I rename the load module as expected
```
ZOWESIS  CSV028I ABEND806-04  JOBNAME=ZOWESIS   STEPNAME=ZOWESIS
         IEA989I SLIP TRAP ID=X806 MATCHED.  JOBNAME=ZOWESIS , ASID=0252.
ZOWESIS  IEA995I SYMPTOM DUMP OUTPUT
ZOWESIS  SYSTEM COMPLETION CODE=806  REASON CODE=00000004
ZOWESIS   TIME=13.53.42  SEQ=39350  CPU=0000  ASID=0252
ZOWESIS   PSW AT TIME OF ERROR  070C1000   81540C1A  ILC 2  INTC 0D
ZOWESIS     NO ACTIVE MODULE FOUND
ZOWESIS     NAME=UNKNOWN
ZOWESIS     DATA AT PSW  01540C14 - 8400181E  0A0D18FB  180C181D
ZOWESIS     GR 0: 00001F00   1: 84806000
ZOWESIS        2: 00000000   3: 00000000
ZOWESIS        4: 00000000   5: 007FE8A0
ZOWESIS        6: 000000FF   7: 00000000
ZOWESIS        8: 7F5BD050   9: 01541140
ZOWESIS        A: 00000000   B: 00000000
ZOWESIS        C: 00000000   D: 7F5BD050
ZOWESIS        E: 84806000   F: 00000004
ZOWESIS   END OF SYMPTOM DUMP
```

Dataset info:
```
Data Set Name  . . . : XXXX.ZOWE.LOADLIB

General Data                          Current Allocation
 Management class . . : MCSYLONG       Allocated cylinders : 10
 Storage class  . . . : SCSYS          Allocated extents . : 1
  Volume serial . . . : SYSW21         Maximum dir. blocks : NOLIMIT
  Device type . . . . : 3390
 Data class . . . . . : **None**
  Organization  . . . : PO            Current Utilization
  Record format . . . : U              Used pages  . . . . : 293
  Record length . . . : 0              % Utilized  . . . . : 16
  Block size  . . . . : 6999           Number of members . : 2
  1st extent cylinders: 10
  Secondary cylinders : 5
  Data set name type  : LIBRARY       Dates
  Data set version  . : 2              Creation date . . . : 2019/12/05
                                       Referenced date . . : 2019/12/12
                                       Expiration date . . : ***None***
```

**Comment by gatogatogato** [comment]
Here you go 
[ZOWESIS.JOBLOG.txt](https://github.com/zowe/zss/files/3956111/ZOWESIS.JOBLOG.txt)

**Comment by ifakhrutdinov** [comment]
Thank you. Okay, now PSW shows key 4.

**Comment by gadyck** [comment]
The failing PSW is at the same point in the code as when it was running with key 8, so the failure is *not* related to the storage key.  It is occurring before the storage key is of concern.

R14 contains x'6FE6' and R15 contains x'1A', so the LLGC R14,0(R15,R14) instruction just stepped over the page boundary.  This is probably a valid issue that needs to be fixed.

**Comment by ifakhrutdinov** [comment]
@gatogatogato I think I may know what the cause of your S0C4.

I'd like to make a change, but I don't know how I'd give you the module.

**Comment by ifakhrutdinov** [comment]
@gadyck Yes, here's the code that causes it

```c
  if (mainParms != NULL && mainParms->textLength > 0) {
    zowelog(NULL, LOG_COMP_STCBASE, ZOWE_LOG_INFO,
            ZIS_LOG_INPUT_PARM_MSG, mainParms);
    zowedump(NULL, LOG_COMP_STCBASE, ZOWE_LOG_INFO,
             (void *)mainParms,
             sizeof(mainParms) + mainParms->textLength);
  }
```

The `sizeof(mainParms)` must be `sizeof(*mainParms)` or `sizeof(ZISMainFunctionParms)`.

**Comment by ifakhrutdinov** [comment]
@gatogatogato 

Below if a ZIP archive with the build from #125 pull request. You'll find a PAX archive inside which you can decompress using `pax -ppx -rf zss-1.8.0-pr-125-1-20191212145708.pax`, The load module will be in `LOADLIB/ZWESIS01`. Copy it using `cp -X LOADLIB/ZWESIS01 "'//XXXX.ZOWE.LOADLIB'"`.

The pax was downloaded from https://gizaartifactory.jfrog.io/gizaartifactory/libs-snapshot-local/org/zowe/zss/1.8.0-PR-125/zss-1.8.0-pr-125-1-20191212145708.pax but you'd need credentials to access that. I think once the PR has been merged you'll be able to access the nightly builds without credentials.

[zss-1.8.0-pr-125-1-20191212145708.pax.zip](https://github.com/zowe/zss/files/3956422/zss-1.8.0-pr-125-1-20191212145708.pax.zip)

CC: @dmitrynikolaev

**Comment by gatogatogato** [comment]
Great job guys, impressive.
I'll try and test the fixed load module tomorrow at the office.

**Comment by gatogatogato** [comment]
Fix seems to be okay, the server now does not crash any more. I'll attach the output from the STC job log for you to inspect.
[ZOWESIS.LOG.txt](https://github.com/zowe/zss/files/3959320/ZOWESIS.LOG.txt)

**Comment by ifakhrutdinov** [comment]
Great news! Thank you for testing it.

**Comment by gatogatogato** [comment]
I dicovered the MODIFY DISPLAY command just a little later. It shows key 4 now as expected:
```
07:47:12  ZWES0220I Modify DISPLAY command received
07:47:12  ZWES0222I Server name - 'ZWESIS_STD      '.
07:47:12           Global area address = 0x11FBD000
07:47:12             Version          = 2
07:47:12             Key              = 4
07:47:12             Subpool          = 228
07:47:12             Size             = 4096
07:47:12             Flags            = 0x00000000
07:47:12             Server address   = 0x19493630
07:47:12             Server ASID      = 0x0221
07:47:12             Server flags     = 0x00000002
07:47:12             ECSA block count = 0
07:47:12             PC-ss PC number  = 0x00182F00
07:47:12             PC-ss seq number = 0x00000001
07:47:12             PC-cp PC number  = 0x00182F01
07:47:12             PC-cp seq number = 0x00000001
07:47:12             PC log level     = 2
```

**Comment by ifakhrutdinov** [comment]
@gatogatogato, can we close this? I think the issue has been fixed.

**Comment by gatogatogato** [comment]
This can be closed
