### ISSUE TITLE
ZSS Cross-Memory Server Starting, version 1.0.5

### ISSUE THREAD

**Issue by jimmschlo89** [zowe/zss#138]
Hello! When starting the Cross Memory Server I run into this issue:
![image](https://user-images.githubusercontent.com/49279914/71851880-28c1a700-309d-11ea-934f-9aec66c0c210.png)

I already saw a post that was fairly similar to this one (https://github.com/zowe/zss/issues/122). I tried uploading the recommended .pax file and replacing the LOADLIB member with the member from the unpaxed file, but that did not change anything. Not sure what to do... any help would be awesome!

Thank you,

James

**Comment by jimmschlo89** [comment]
@ifakhrutdinov This is the issue I just opened up.

**Comment by ifakhrutdinov** [comment]
@jimmschlo89 
* Have you added the appropriate PPT entry for the ZWESIS01 module? See [Add PPT entries to the system PARMLIB](https://docs.zowe.org/stable/user-guide/configure-zowe-runtime.html#manually-installing-the-zowe-cross-memory-server)
* Has the load load library been APF-autrhorized?  See [Add the load libraries to the APF authorization list](https://docs.zowe.org/stable/user-guide/configure-zowe-runtime.html#manually-installing-the-zowe-cross-memory-server)

**Comment by jimmschlo89** [comment]
@ifakhrutdinov Yes, both have been done.

**Comment by ifakhrutdinov** [comment]
@jimmschlo89 the items I mentioned are the only ones that could have caused that error.

Can you please do the following:
* Issue `D PROG,APF,DSNAME=your-dataset-name` and copy-paste the output
* Issue `D PPT,NAME=ZWES*` and copy-paste the output
* Go to the load library in ISPF and make a screenshot of the list of members, similar to:
```
VIEW              XXXXX.DEV.LOADLIB                     Row 0000004 of 0000005 
Command ===>                                                  Scroll ===> CSR  
           Name     Prompt        Alias-of     Size      TTR     AC   AM   RM  
_________ ZWESAUX                            00060E50   003F99   01    64  ANY 
_________ ZWESIS01                           0007C300   003F98   01    64  ANY 
          **End**                                                              
```

**Comment by jimmschlo89** [comment]
![image](https://user-images.githubusercontent.com/49279914/71909719-32e3b400-3136-11ea-95cc-2c7b823201cb.png)

![image](https://user-images.githubusercontent.com/49279914/71909728-35dea480-3136-11ea-9a2e-2bf4e2e4754d.png)

![image](https://user-images.githubusercontent.com/49279914/71909739-3a0ac200-3136-11ea-8c9c-d987c975f5cd.png)

**Comment by ifakhrutdinov** [comment]
@jimmschlo89 I can see that there is no PPT entry or the configuration hasn't been refreshed.

If you've added the entries to the config member, please issue the following command: `SET SCH=xx`, where `xx` is the suffix of the SCHED member you added the entries to.

For example, if the member is `SCHEDK1`, the command will be `SET SCH=K1`

**Comment by jimmschlo89** [comment]
@ifakhrutdinov I've added the entries to that member, its called SCHED00. Even after I do a `/SET SCH=00` (which works), I get the same response from `/D PPT,NAME=ZWES*`

**Comment by jimmschlo89** [comment]
@ifakhrutdinov Ok, all of that above is resolved. ZWESIS01 now starts. However ZWESAUX does not.

**Comment by ifakhrutdinov** [comment]
@jimmschlo89 it's not started by default. It's used for some extensions and it won't prevent ZSS from using the cross-memory server.
