### ISSUE TITLE
MALLOC Issue?

### ISSUE THREAD

**Issue by jimmschlo89** [zowe/zss#140]
I'm seeing about 5 of these messages for different plugins within zowe. Not sure what they mean. Any help would be great!

![image](https://user-images.githubusercontent.com/49279914/71931995-a4d2f200-3164-11ea-8783-6f5a497a2086.png)

**Comment by 1000TurquoisePogs** [comment]
Fixed in https://github.com/zowe/zowe-common-c/pull/122 which I would expect to see in 1.9
