### ISSUE TITLE
Support z/OS 2.4 in ZSS

### ISSUE THREAD

**Issue by ifakhrutdinov** [zowe/zss#15]
Currently there is an explicit check that prevents ZSS from starting on z/OS > 2.3. This check needs to be changed to include 2.4.

**Comment by std4lqi** [comment]
Can I know whether it could be part of the next release 1.0.2? Thanks!

**Comment by ifakhrutdinov** [comment]
@1000TurquoisePogs do we still have time before the code freeze? I made a PR. Although I don't have a 2.4  system to test, I got the new constant value form a z/OS 2.4 system at IBM.

**Comment by std4lqi** [comment]
Hi, can I know any update of merging it into the next release? Thanks!

**Comment by ifakhrutdinov** [comment]
The fix been merged to the staging branch and should be available in next release.

**Comment by Joe-Winchester** [comment]
@ifakhrutdinov - would it be possible to get a build that accepts z/OS 2.5 as a platform ?  It's hard coded to stop at 2.4 and for early testing it'd be good to have 2.5 tolerated.
**Note** - this does in any way announce or disclose the existence of a z/OS release that may or may not be called 2.5 and/or whether that may or may not become available at an undefined date in the future.

**Comment by ifakhrutdinov** [comment]
@Joe-Winchester sure, https://github.com/zowe/zss/pull/145

**Comment by ifakhrutdinov** [comment]
@Joe-Winchester I think the pax should be available [here](https://zowe.jfrog.io/zowe/webapp/#/builds/zss%20::%20PR-145/1/1579881083841/published%20/zss%20::%20PR-145)

**Comment by Tam-Lin** [comment]
Why is there a maximum level of z/OS check anyway?  I can understand checking for a minimum supported level, but why check for a maximum level?

**Comment by ifakhrutdinov** [comment]
I believe some of the data structures/fields used in the code may potentially change which likely happens with a new version z/OS. So limiting the max version ensures the code doesn't behave unexpectedly.

**Comment by Tam-Lin** [comment]
One of the foundational values of z/OS is backwards compatibility; it's incredibly rare for IBM to make a change to a new level of z/OS that will prevent older software from running on it.  It makes sense to have functional dependencies on being on or above a given level of z/OS; it doesn't make sense to have a limit on a maximum level of z/OS.  There is software that was written in the 1960s that will run on z/OS today.

**Comment by hogstrom** [comment]
I suggest that instead of hard stopping, issue a ZWEnnnnW message that indicates that ZSS is starting above a tested z/OS version number and continue.

**Comment by hogstrom** [comment]
This will continue to be an issue at every z/OS release cycle.  See previous comment on recommended approach.

**Comment by JoeNemo** [comment]
This is fixed and is a stale issue.
