### ISSUE TITLE
zis-plugin-install.sh fails to propagate return code to caller

### ISSUE THREAD

**Issue by nosrednayduj** [zowe/zss#228]
If you give an invalid folder for the parmlib, error messages are printed, and obviously values are not entered into the zowe parmlib, and a zero return code is returned to the caller (so the caller thinks that all was well).

zis-plugin-install.sh extended-install myplugin/zisServer/loadlib nonexistantfolder

> info: updating RSQA.IZP.IZPS011.PARMLIB(ZWESIP00) with the values from  nonexistantfolder/*
> update_parmlib 4294967101: zis-parmlib-update.sh 269: FSUM7343 cannot open "nonexistantfolder/*" for input: EDC5135I Not a directory.
> error: script failed, RC = 1

Yet the return value to the original caller is zero despite this printout.

It looks like the culprit might be zis-parmlib-update.sh; I added some print statements to try to track this down but did not come to a conclusion about where the real bug is.

**Comment by 1000TurquoisePogs** [comment]
Closing this as it seems no longer relevant in v2 which is where this user is migrating to.
