### ISSUE TITLE
ZSS API allows enqueued dataset to be updated by another user 

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zss#236]
I used the WEBUI Editor to edit a dataset, which takes an exclusive SPFEDIT ENQ, visible in z/OS as 
```
SDSF ENQ DISPLAY  MV3B     MV3B      MAJ SPFEDIT       LINE 6-6 (6)           
COMMAND INPUT ===>                                            SCROLL ===> CSR 
NP   MINOR                                                Major    Req JobName
     USER.PARMLIB                                TESTMEM  SPFEDIT  EXC SZ1    
```
Then another user used Insomnia to POST an updated body to that same member, and this succeeded.  This should not be permitted.

**Comment by John-A-Davies** [comment]
I think this is because, although the ENQ prevents other jobs from accessing the locked dataset, it does not prevent other users of the zssServer job itself from accessing them, even though the ENQ is taken in the name of the original user.

**Comment by John-A-Davies** [comment]
```
SDSF PROCESS DISPLAY  MV3B     ALL                      COMMAND ISSUED   
COMMAND INPUT ===>                                            SCROLL ===>
RESPONSE=MV3B                                                            
 BPXO070I 11.26.13 DISPLAY OMVS 250                                      
 OMVS     0011 ACTIVE             OMVS=(3B,00,DB,JV)                     
 USER     JOBNAME  ASID        PID       PPID STATE   START     CT_SECS  
 DAVIESJ  SZ1      0099   33620400      65972 HF------ 10.39.48      .1  
   LATCHWAITPID=         0 CMD=./zssServer ../defaults/serverConfig/ser  
  THREAD_ID        TCB@     PRI_JOB  USERNAME   ACC_TIME SC  STATE       
  1530E80000000000 009F8368 OMVS                    .034 SEL  FU         
  152FD00000000009 009F8020 OMVS     DAVIESJ        .001 SOP JD          
  152C780000000015 009CDE88 OMVS     MARHOLL        .001 SLP JS          
```

**Comment by John-A-Davies** [comment]
I have a fix for this.

**Comment by ifakhrutdinov** [comment]
@John-A-Davies is this for GA code? I don't think we do acquire enqueues.

**Comment by John-A-Davies** [comment]
Yes, the fix is targeted at GA code.  Please refer to line 1107 in file `datasetjson.c`.

**Comment by John-A-Davies** [comment]
@struga0258 This would make a good test case.

**Comment by ifakhrutdinov** [comment]
Here's the code around 1107:
```c
    ShortLivedHeap *slh = makeShortLivedHeap(blockSize,maxBlockCount);
    char errorBuffer[2048];
    zowelog(NULL, LOG_COMP_RESTDATASET, ZOWE_LOG_DEBUG, "UPDATE DATASET: before JSON parse dataLength=0x%x\n",bodyLength);
    Json *json = jsonParseUnterminatedString(slh, 
                                             convertedBody, translationLength,
                                             errorBuffer, sizeof(errorBuffer));
    if (json) {
      if (jsonIsObject(json)){
        updateDatasetWithJSON(response, jsonAsObject(json), absolutePath);
      } else{
        zowelog(NULL, LOG_COMP_RESTDATASET, ZOWE_LOG_DEBUG, "*** INTERNAL ERROR *** message is JSON, but not an object\n");
      }
    }
```
What is the issue here?

**Comment by struga0258** [comment]
@John-A-Davies I will create a test ticket and start writing automation. thanks!

**Comment by ifakhrutdinov** [comment]
@John-A-Davies but there are no dataset enqueues in the GA code and the title mentions them. Why do we need an issue for code which hasn't been written/merged?

* If there is an issue in the GA code, please provide the instructions applicable to it, also correct the title.
* If this is applicable to future code only, then we need to close the issue.

**Comment by John-A-Davies** [comment]
You're right - this is not a defect in GA code.  It was a lack-of-feature in the new code in my `dsedit#498` branch.

The code to fix this issue has already been added, in this branch:  https://github.com/zowe/zowe-common-c/blob/dsedit%23498/c/datasetjson.c, from line 1096.

I added this issue as a placeholder, to make sure it was not forgotten.

Closing as it's now fixed.
