### ISSUE TITLE
ZSS is not able to read SO token on ACF2

### ISSUE THREAD

**Issue by achmelo** [zowe/zss#294]
This feature properly works for TSS and RACF but on ACF2(marist-2) we get an error message ZWES1030W Server startup problem: Could not load the JWT key 'ZWETOKEN' from token 'jwtsecret': rc '12', p11rc '0', p11Rsn '0' . 
More info in https://wash.zowe.org:8443/job/zowe-install-test/view/change-requests/job/PR-2053/18/consoleFull
PR https://github.com/zowe/zowe-install-packaging/pull/2053

**Comment by 1000TurquoisePogs** [comment]
Seems to be known by jack at https://github.com/zowe/zowe-install-packaging/issues/2052 but not sure what the fix will be yet.

**Comment by achmelo** [comment]
Issue 2052 has been solved. Now the issue is that SO token is being created but for some reason ZSS is not able to read it on ACF2. The same setup works and being tested on TSS and RACF. I would like to ask you for help in debugging this issue.

**Comment by achmelo** [comment]
you can see in the logs I provided that token ZWETOKEN with label jwtsecret exists, so the error is strange: ZWES1030W Server startup problem: Could not load the JWT key 'ZWETOKEN' from token 'jwtsecret': rc '12', p11rc '0', p11Rsn '0' .

 P11TOKEN BIND TOKEN(ZWETOKEN) CERTDATA(ZWESVUSR.JWTSCRT)
     Token name: ZWETOKEN
  
     Sequence Labels                                Attributes
     -------- ------------------------------------- -----------------------------
     00000001 TKDS:jwtsecret                        Usage(Personal) Default(No)
              ACF2:jwtsecret                        PubKey(Yes) PvtKey(No)
                                                    ACF2USER(ZWESVUSR)
  
     ?
       P11TOKEN LIST TOKEN(ZWETOKEN)
     Token name: ZWETOKEN
  
     Sequence Labels                                Attributes
     -------- ------------------------------------- -----------------------------
     00000001 TKDS:jwtsecret                        Usage(Personal) Default(No)
              ACF2:jwtsecret                        PubKey(Yes) PvtKey(No)
                                                    ACF2USER(ZWESVUSR)

**Comment by achmelo** [comment]
There is an issue with my latest updates related to this https://github.com/zowe/zowe-install-packaging/issues/1779

**Comment by 1000TurquoisePogs** [comment]
OK, making a debug build for this but what I see so far is that jwt.c uses any of these commands to work https://github.com/zowe/zowe-common-c/blob/master/jwt/rscrypto/rs_icsfp11.c#L16-L38
Basically all the function calls that start with "rs_icsfp11" within jwt.c

**Comment by achmelo** [comment]
Were you able to find something with debug build?

**Comment by balhar-jakub** [comment]
@achmelo Is this still valid as we now provide the JWT token with the REST API?

**Comment by achmelo** [comment]
not valid anymore
