### ISSUE TITLE
Need to run ZWESAUX for zACS

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zss#297]
According to this image, it seems, that ZWESAUX is managing PC calls:
![image](https://user-images.githubusercontent.com/66114686/118114852-6f898480-b3e8-11eb-8ec0-432dd849c815.png)

So I need to have ZWESAUX running to be able to perform PC (program call) scan, which I need for IBM Authorized Code Scanner (zACS).

I read the documentation and search in these issues and I understand, that this module is not intended to be executed by user otherwise it will fail. The execution is controlled by the cross memory server (ZWESIS01).

Is there some way how to run ZWESAUX?

I will appreciate any idea or hint, thanks.

**Comment by 1000TurquoisePogs** [comment]
You need a ZIS plugin to invoke AUX, so you can try this one
https://github.com/ifakhrutdinov/zss-sample-plugin/tree/master/zisServer
But without any plugins, ZIS makes one or two PC calls by itself.
