### ISSUE TITLE
zssServer failed with new zos version

### ISSUE THREAD

**Issue by rjmaomao** [zowe/zss#33]
Hi, 

I'm running into issue where zssServer failed to start. In log file I saw following info. I know zOS 2.4 is not released yet. But could you please still take a look? Thanks!

_168:/Z2/var/zowert/1.1.0/zlux-app-server/log $ cat  zssServer-2019-05-01-14-17.log
CEE5207E The signal SIGABRT was received.
error: z/OS version = 0x01020400, max supported version = 0x01020300 - CAA fields require verification_

**Comment by dmitrynikolaev** [comment]
z/OS 2.4 support has been added to Zowe v1.2.0

https://github.com/zowe/zss/issues/15

**Comment by rjmaomao** [comment]
Thank you, I'll try 1.2.0.

**Comment by rjmaomao** [comment]
Verified 1.2.0 fixed the issue. Thanks!
