### ISSUE TITLE
Error ZSS 500 on desktop login

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zss#409]
Hi, 
I am receiving the ZSS error 500 when trying to log to the desktop:
```
"org.zowe.zlux.auth.safsso: ZSS 500
{"messages":[{"messageType":"ERROR","messageNumber":"ZWEAM701E","messageContent":"The request to the URL '/api/v1/zss/login' has failed: ZuulException: Forwarding error caused by: NoHttpResponseException: some.network.net:8542 failed to respond","messageKey":"org.zowe.apiml.common.internalRequestError"}]}"
```

Also I have noticed, that I am receiving Connection reset for curl POST:

```
curl -u user:password -X POST http://some.network.net:8542/login          
curl: (56) Recv failure: EDC8121I Connection reset.     
```
instance.env: ```ZOWE_ZSS_SERVER_PORT=8542```
Zowe job log: ```ZWES1013I ZSS Server has started. Version '1.25.0+20211013'```

Any help is appreciated.
Thanks, Martin

**Comment by 1000TurquoisePogs** [comment]
Hi Martin,
Are you sure ZSS is using http? These days, it uses HTTPS by default.

**Comment by 1000TurquoisePogs** [comment]
Do you get code ZWES1601I  or ZWES1605W  in the logs?

**Comment by Martin-Zeithaml** [comment]
I can find the first one:
```ZWES1601I Server is ready to accept JWT without fallback to legacy tokens```

**Comment by 1000TurquoisePogs** [comment]
Can you try turning on zss low-level logging to see if you get any good http-level info?
https://github.com/zowe/zlux/wiki/Loggers:-Core-loggers-for-App-Server-&-ZSS#loggers-for-zss-server-core
it's going to need an edit to `workspace/app-server/serverConfig/server.json` such as
"logLevels": {"_zss.traceLevel": 5}

What I'm curious about is... is it sending a malformed HTTP message? Perhaps there's a bad header or something. Don't know which trace option is best, so set all of them to 5

**Comment by Martin-Zeithaml** [comment]
I know these debug options, this was already set, but I was not able to determine the problem:
```
   "_zss.traceLevel": 5,
     "_zss.httpDispatchTrace": 5,
     "_zss.socketTrace": 5,
     "_zss.httpSocketTrace": 5,
     "_zss.httpParseTrace": 5,
     "_zss.httpHeadersTrace": 5,
     "_zss.httpCloseConversationTrace": 5,
     "_zss.httpAuthTrace": 5
```

I will send you the job log.

**Comment by 1000TurquoisePogs** [comment]
I believe Martin said that upgrading to 1.27.0 fixed this specific problem, but others have reported similar issues so there still may be a bug somewhere.

**Comment by Martin-Zeithaml** [comment]
Yes, I can confirm that upgrading to 1.27.0 fixed that. And the Editor is working fine.

**Comment by Martin-Zeithaml** [comment]
After upgrading to 1.27.1 there was an issue with accessing JES/MVS/USS explorers. The problem was solved by using other certificates (certificates from working LPAR with NONSTRICT_VERIFY_CERTIFICATES option). Since the problem was on customer's machine, we did not get the old certificates for analysis so the root of the problem is unknown.
