### ISSUE TITLE
Security issue with a /verify endpoint for IDT validation

### ISSUE THREAD

**Issue by JirkaAichler** [zowe/zss#415]
ZSS `/verify` endpoint is currently accepting only IDT that it should be validated.

It should also accept an APPLID of the service and check whether it matches the APPLID for which the token is valid.

**Comment by 1000TurquoisePogs** [comment]
Is it being resolved here? https://github.com/zowe/zss/pull/403

**Comment by JirkaAichler** [comment]
No, it solves generating IDT and not validating. 

https://github.com/zowe/api-layer/pull/2083 is adding an APPLID to verify ZSS requests.

**Comment by JirkaAichler** [comment]
I just tested it and it seems to be working fine. Thanks, everyone!  Closing issue.
