### ISSUE TITLE
Reduce / Eliminate ZWES1606W under normal circumstances

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zss#425]
# Background
In 1.27 JWT becomes automatic and therefore the default. It became that way because the requirements for it were simplified where the PKCS11 region is no longer needed. However, ZWES needs to contact ZWEAG to initialize JWT use, and ZWEAG is not ready for this call as quickly as ZWES, so a warning is issued and a retry is attempted every 30 seconds until ready. At this time we don't have a way to separate normal retries from a sign that there's a problem, so ZWES1606W is both seen in normal startup 

# Goal
Don't show warnings if nothing is wrong, get rid of ZWES1606W under normal behavior, but still show it if something is wrong.

# Ideas
Should this just be an INFO message?
Should this message stop printing after some time because people can tell if the issue stopped by another message that tells you JWT is now ready?

**Comment by Martin-Zeithaml** [comment]
Reduction done in #663.
