### ISSUE TITLE
ZSS- UnixFile GET metadata API  request gives - 404- File not found 

### ISSUE THREAD

**Issue by AdarshdeepCheema** [zowe/zss#458]
open the API Catalog and try to use the ZSS Unixfile API to get the metadata of any file/directory

you will get 404 for all requests for the following FAILING SCENARIOS 

FAILING CASE:
1) when we have '/' in the directory path
directory -> u/adarsh
filename -> testing
=> curl -X GET "https://TVT5xxx.svl.xxx.com:7554/zss/api/v1/unixfile/metadata/u%2Fadarsh/testing" -H "accept: application/json"

2) when we have one or more spaces in the directory path or file name
directory -> u
filename -> a b c d
=> curl -X GET "https://TVTxxx.svl.xxx.com:7554/zss/api/v1/unixfile/metadata/u/a%20b%20c%20d-H "accept: application/json"

PASSING CASE: 
directory -> u
filename -> adarsh
=> curl -X GET "https://TVTxxx.svl.xxx.com:7554/zss/api/v1/unixfile/metadata/u/adarsh" -H "accept: application/json"

It seems like ZSS does not handle **%2F** and **%20b** in the request URL

**Comment by Martin-Zeithaml** [comment]
Seems to be working now (tested only v2):

```
curl -X GET "https://skynet:800/zss/api/v1/unixfile/metadata/j%2Fjconnor%2Ftest%2Fs%20p%20a%20c%20e%20s" -H "accept: application/json"

{"path":"/j/jconnor/test/s p a c e s","directory":true,"size":8192,"ccsid":0,"createdAt":"2029-09-10T09:04:07","mode":755,"owner":"JCONNOR","group":"RESISTAN"}
```
