### ISSUE TITLE
Using other SAF Class than 'ZOWE' does not work (ZWESIP00)

### ISSUE THREAD

**Issue by lv198** [zowe/zss#485]
Typically, in my company, SAF Classes of optional software products have a '$' as first character in their name, for example '$ZOWE' instead of 'ZOWE'.
When using $ZOWE instead of ZOWE as SAF CLASS, Zowe gets a service error, 'Problem checking access permissions'.

As the values are customizable, this should work.

Error message example:
2022-07-05 13:38:33.117 <ZWED:66587> ZWESVUSR WARN (org.zowe.zlux.auth.safsso,zssHandler.js:310) User XXXXXX, authorization problem: Service error:

**Comment by 1000TurquoisePogs** [comment]
Hello,

> As the values are customizable, this should work.

Where do you see instructions within Zowe about customizing the name of the class away from "ZOWE"?
I believe it must be ZOWE, https://docs.zowe.org/stable/user-guide/mvd-configuration/#defining-the-racf-zowe-class
z/OS 2.5 actually ships with class ZOWE defined I believe.

**Comment by lv198** [comment]
Hello @1000TurquoisePogs 

If it must be Zowe, why are the values in member ZWESIP00 customizable and not hardcoded? 

Also, I'd be interested in documentation about the introduction of class Zowe in z/OS 2.5. 
That would help me in the discussion with our RACF team (it's not my idea to use $ZOWE instead of ZOWE, I'd rather use what the product suggests ...).

**Comment by 1000TurquoisePogs** [comment]
ZWESIP00 customization may date back to before we knew what the name of the project would be, but there are other places where ZOWE is hardcoded, so changing it in ZWESIP00 will break when other places still look for ZOWE.
I found this online https://www.newera.com/INFO/090921_V2R5_Part_2.pdf by Marna Walle of IBM and on page 35 she goes into detail about RACF actions to take to migrate from a dynamic zowe class to the one they have builtin.

**Comment by lv198** [comment]
Okay thank you that helps me a lot
