### ISSUE TITLE
zssServer64 Program Control Attribute not set SMPe install

### ISSUE THREAD

**Issue by BartS07** [zowe/zss#492]
Zowe V2 doc says it is recommended to run the ZSS in 64 bit mode, and it also mentions the zowe.yaml setting to update.

But the Program Control Attribute is not set for components/zss/bin/zssServer64 in the SMPe installed version of Zowe. 

From the ZWESLSTC output:

BPXTLS failed: rc=-1, return code=139, reason code=0x0be802af                                                  
Error: service has no impersonation; make sure process user has sufficient authority:                          
  z/OS: program control flag must be set, UPDATE access to BPX.SERVER and BPX.DAEMON SAF resources is required 
  Other platforms: impersonation is not supported                                                              
BPXTLS failed: rc=-1, return code=139, reason code=0x0be802af                                                  
Error: service has no impersonation; make sure process user has sufficient authority:                          
  z/OS: program control flag must be set, UPDATE access to BPX.SERVER and BPX.DAEMON SAF resources is required 
  Other platforms: impersonation is not supported                                                              

**Details**
 - Zowe version: v2.1.0

**Additional context**
Setting the Program Control Attribute manually solved the issue.

**Comment by 1000TurquoisePogs** [comment]
Hi @BartS07 thanks for noticing, you're right!
I spotted that we just fixed this https://github.com/zowe/zss/blame/v2.x/staging/.pax/pre-packaging.sh#L41 but it wont be there until v2.3
The good news about v2.3 is there's going to be other improvements under the hood too. Namely, if you run zowe with the zowe.yaml property `zowe.useConfigmgr=true` it should startup faster, have config validation, and more... I've got to write a proper document on the subject of configmgr.
