### ISSUE TITLE
Can't Copy jcl file to PROCLIB 

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zss#5]
The `cp` command on Line 24 of `zowe-xmem-deploy-sh` fails to write to USER.Z23B.PROCLIB on a zD&T system.

Reason for failure:
There is a restriction is USS which means you can't write to a z/OS dataset if any process has it allocated, even if only for READ.  USER.Z23B.PROCLIB is in use by another user.  The other user of USER.Z23B.PROCLIB is anyone who logs on with the TSO PROC called ISPFPROC, which allocates USER.Z23B.PROCLIB to your TSO userid.

So the following datasets used in ISPFPROC will fail as a PROCLIB candidate:

USER.Z23B.PROCLIB
FEU.Z23B.PROCLIB 
ADCD.Z23B.PROCLIB

on our zD&T systems.  Any other system that does this will have the same problem.

A solution is to avoid using USS to make the copy.  The main zowe install does this using a REXX EXEC, so the failing line 24 could be replaced by a call to the shell script which uses that REXX.

`if ${ZSS}/../scripts/zowe-copy-proc.sh ${ZSS}/SAMPLIB/${jclfile} $proclib $member`

**Comment by John-A-Davies** [comment]
Notes:
1.  This is not specific to zD&T systems; it applies to any system where the target dataset is allocated to another user, even as SHR.
2.  The same problem could occur for deploying to PARMLIB and LOADLIB.

**Comment by dmitrynikolaev** [comment]
There're hard-coded references to ZOWESVR.JCL in zowe-copy-proc.sh, and the script relies on ocopyshr.clist copied to a temp dataset beforehand.

Since APF server installation is supposed to be a separate script, we can't use that directly.

**Comment by dmitrynikolaev** [comment]
We've encountered multiple errors that apparently are related to autoencoding.
Investigating what caused that.

**Comment by dmitrynikolaev** [comment]
`scripts/zowe-copy-proc.sh` can't be re-used for xmem installation:

    * we need to deploy PARMLIB, LOADLIB and PROCLIB not only PROCLIB

    * the existing script works in TEXT mode only

    * it expects a certain context (variables and temp datasets) set up in `zowe-install.sh`

**Comment by dmitrynikolaev** [comment]
https://github.com/zowe/zowe-install-packaging/pull/387
