### ISSUE TITLE
Zss internal error accessing .components.zss.'productReg', err=101

### ISSUE THREAD

**Issue by ojcelis** [zowe/zss#512]
Getting product registration error message "internal error accessing .components.zss.'productReg', err=101" while testing v2.3-RC3

**Comment by 1000TurquoisePogs** [comment]
This is due to a lookup that expects this parameter to be mandatory and therefore prints an error when its not provided.
In reality, this "error" is unimportant. its an optional parameter that when missing causes no issue.
It should still be fixed so that people do not continue to discover this.
