### ISSUE TITLE
S0C4 abends during startup, zss won't start

### ISSUE THREAD

**Issue by BartS07** [zowe/zss#527]
- UO02053/UO02054 V2.3.1 applied. 
- ZWESISTC: ZWES0001I ZSS Cross-Memory Server starting, version is 2.3.0+20220912 
- ZWESLSTC running in 64 bit mode
- ZWESLSTC: no ZWES1013I message and there is also no ZWES1014I message
- ZWESLSTC: several retries zss start generating messages (ending with message ZWEL0038E max retries reached):

IDI0001I Fault Analyzer V14R1M15 (UI77735 2021/10/19) invoked by IDIXDCAP using SYS1.FLTANA.PARMLIB(IDICNF00) 
IDI0053I Fault history file entry suppressed due to: DUMMY history file specification                         
IDI0002I Module ./zssServer, program quickjs#C, offset X'26D88': PIC 0004 (Abend S0C4 - Protection Exception) 
<...>
2022-10-18 03:39:26 <ZWELS:50333270> ZWESVUSR INFO (zwe-internal-start-component) starting component zss ...           
2022-10-18 05:40:16 <ZWELNCH:67109202> ZWESVUSR INFO ZWEL0004I component zss(83886419) terminated, status = 0          
2022-10-18 05:40:16 <ZWELNCH:67109202> ZWESVUSR INFO ZWEL0005I next attempt to restart component zss in 1 seconds      
2022-10-18 05:40:17 <ZWELNCH:67109202> ZWESVUSR INFO ZWEL0001I component zss started

**Comment by 1000TurquoisePogs** [comment]
we've seen this result in CEEDUMP files being put into the zowe runtime directory. If you see one, can you upload it? It's very useful here.

**Comment by BartS07** [comment]
Unfortunately I don't see any.

**Comment by 1000TurquoisePogs** [comment]
you may have the environment variable "_CEE_DMPTARG" set (would show up in job log) and if so, the CEEDUMP will instead be located in that directory.

**Comment by 1000TurquoisePogs** [comment]
Another possibility is the file is in runtime_directory/components/zss/bin or just runtime_directory/components/zss

**Comment by BartS07** [comment]
Variable _CEE_DMPTARG is not set. 
Don't see any CEEDUMP in the runtime_directory/components/zss/bin or runtime_directory/components/zss

**Comment by BartS07** [comment]
Zowe upgrade to 2.4.0 fixed this issue. Strange, maybe v2.3.1  was not SMPe packaged in the right order?
