### ISSUE TITLE
ZSS component failure to start

### ISSUE THREAD

**Issue by RadekNavratil** [zowe/zss#539]
Hello guys,

I am new to Zowe, installing version 2.2 on zOS 2.4 on our test image before deploy to production.
ZSS component failure to start with messages below.
Keystore was generated of default values using zwe init certificate and is type PKCS12
Certificate is functional as I have connection from web browser to gateway component and appserver component.
ZSS component setting in my zowe.yaml is default, displayed below.
May I ask you to advice what is wrong and what to check, thank you.

ERROR:
ZWES1013I ZSS Server has started. Version '2.2.0+20220713' 31-bit               
fallback to default server settings                                             
ZWES1038I Server timeouts file '/u/zwesvusr/workspace/app-server/serverConfig/timeouts.json' either not found or invalid JSON. ZSS sessions will use the default
ZWES1061I TLS settings: keyring '/u/zwesvusr/keystore/localhost/localhost.keystore.p12', label 'localhost', password '****', stash '(no stash)' 
ZWES1060W Failed to init TLS environment, rc=1(Handle is not valid)             
ZWES1065E Failed to configure https server, check agent https settings   

my zowe.yaml:
zss:                                 
  enabled: true                      
  port: 7557                         
  crossMemoryServerName: ZWESIS_STD  
  tls: true                          
  agent:                             
    jwt:                             
      fallback: true

**Comment by balhar-jakub** [comment]
@1000TurquoisePogs Can you move this issue to the ZSS repository please?

**Comment by 1000TurquoisePogs** [comment]
What version of Java are you using?
You have probably been hit by this https://github.com/zowe/docs-site/issues/2459

**Comment by pablocarle** [comment]
Hi, it seems we are also running into this issue, are there any news about it?

**Comment by GilPen** [comment]
Hello 

I'm running the same issue in one of our partition. On some other partitions, the same  ZOWE version 1.27.1 runs correctly.

The java version we are using is SR7FP20. So I  tried to upgrade the java version, the same problem appears. So I tried to downgrade the java version SR7FP11, the same appears too.

We are using ZOWE under our development partition and starts to develop our own API developpers. We really need more significative errors messages with a procedure for an error messageID for the installations.

Regards
Gilles Peniguel

**Comment by RadekNavratil** [comment]
Hello guys, not sure if this will work for you, but my problem was with certificate.pem statement, I had to break it into two lines.

NOT OK:
  pem:                                                                           
    key:                                                                         
    certificate:                                                                 
    certificateAuthorities: safkeyring:////ZWESVUSR/ZoweKeyring&HLAG_2012_RootCA 

OK:

 pem:                                                     
   key: '""'                                              
   certificate: '""'                                      
   certificateAuthorities: >-                             
     safkeyring:////ZWESVUSR/ZoweKeyring&HLAG_2012_RootCA

**Comment by GilPen** [comment]
Hello 

Thank you very much  for answer, but I'm not using a keyring. The certificates are put on USS directory.

Regards
Gilles

**Comment by GilPen** [comment]
Hello

For experiment, I deactivated the TLS in instance.env  file and now the ZSS port 8542 is listening but on the localhost interface 127.0.0.1.

ZWESZ1   009D43BE 127.0.0.1..8542        0.0.0.0..0             Listen

I suppose it's not the good interface because it's not routable. Do you  confirm ?

So I try to change the IP/DNS on the server.json file but whatever I code, port 8542 always bind on the localhost.
