### ISSUE TITLE
ZSS jsonArrayGetItem at statement 1737 Abend S0C4

### ISSUE THREAD

**Issue by rayhand1** [zowe/zss#541]
**Describe the bug**
This is a new install of ZOWE.  Applied all maint and now up to 2.4.0
At zss startup I am getting the following error and zss fails to start

zssServer.sh removing /global/zowe/logs/zssServer-2022-11-21-15-48.log                                                   
ZWES_LOG_FILE=/global/zowe/logs/zssServer-2022-11-22-19-15.log                                                           
CEE3204S The system detected a protection exception (System Completion Code=0C4).                                        
         From entry point jsonArrayGetItem at statement 1737 at compile unit offset +0000002C at entry offset +0000002C  
         at address 32FE8ED4.                                                                                            

IDI0002I Module ./zssServer, program json#C, offset X'679C': Abend S0C4-X'11' (Page-Translation Exception)
ZWED_NODE_LOG_FILE=/global/zowe/logs/appServer-2022-11-22-19-15.log                                       
jar file: /usr/lpp/zowe/components/discovery/bin/discovery-service-lite.jar                               
ZWES1013I ZSS Server has started. Version '2.4.0+20221005' 31-bit                                         
Configuration is Valid                                                                                    

**Steps to Reproduce**

1. just startup of ZWESLSTC

**Expected behavior**

**Screenshots (if needed)**

**Describe your environment**
  This is a z/os 2.4 system
  ZOWE 2.4.0
  SMPE install
  Node.js 16.17.0
  java version "1.8.0_291"

**Comment by 1000TurquoisePogs** [comment]
Can you post to myself and/or @JoeNemo the zowe.yaml you use and the joblog? If you have a CEEDUMP file (at the root of your runtime directory) that will also be helpful. If you want to share these privately, you can also send them to me privately in the OMP slack, or over at email via  sgrady at rocketsoftware.com

**Comment by rayhand1** [comment]
[ZOWE.YAML.txt](https://github.com/zowe/zss/files/10070870/ZOWE.YAML.txt)
[ZWESISTC.OUTPUT.txt](https://github.com/zowe/zss/files/10070871/ZWESISTC.OUTPUT.txt)
[ZWESLSTC.OUTPUT.txt](https://github.com/zowe/zss/files/10070872/ZWESLSTC.OUTPUT.txt)
I was not sure how to post to you or Joe so i put the files here.

**Comment by 1000TurquoisePogs** [comment]
Can you try running with
```
  zss:
    enabled: true
    port: 7557
    crossMemoryServerName: ZWESIS_STD
    tls: true
```

Currently you have `tls: false` and the difference does have an impact on a particular array read, so perhaps this is the cause though it's not clear at this point without more tracing (which I'll look into) or a CEEDUMP file.

**Comment by rayhand1** [comment]
I put a CEEDUMP DD in the started task and restarted it and while it took the S0C4 it did not generate a dump.
Do I need to add anything else?
I do have fault analyzer dumps.  Would that work?

**Comment by 1000TurquoisePogs** [comment]
It's unrelated to the DD statements. CEEDUMP files get generated by the system in the directory that a failure occurred at, when possible. It could be in /usr/lpp/zowe or /usr/lpp/zowe/components/zss or /usr/lpp/zowe/components/zss/bin
If none of the above, perhaps the fault analyzer dump is useful. I'll certainly look at it or find someone who can.

**Comment by rayhand1** [comment]
[CEEDUMP.txt](https://github.com/zowe/zss/files/10071034/CEEDUMP.txt)
I found it, thanks

**Comment by rayhand1** [comment]
Great job, the S0C4 is gone.
I can logon to the zowe desktop thru my browser but take errors on everything except the tn3270 and the api catalog.
Editor gets An unknown error occured: undefined
IP explorer gives me Error: unauthorized
JES explorer takes me to a ZOWE logon screen and I get Unexpected token '<', "<h1>Resour"... is not valid JSON
MVS explorer behaves the same as the JES explorer.
USS explorer behaves the same as the JES explorer.

Do you want me to open individual tickets for each of these?

Thanks for all the help.

**Comment by rayhand1** [comment]
sorry did not mean to bold all that and make the font so big

**Comment by 1000TurquoisePogs** [comment]
Interesting, there must be a weird but with `tls: false` that I can look into.
For your next error, keep in mind that the explorers depend upon the mediation layer. Therefore, you should access the Desktop via the mediation layer in order to make them work. When you access the Desktop directly instead, you get these issues you describe.

That is to say,
Don't go to the Desktop via https://host:7556/
Do go to the Desktop via https://host:7554/zlux/ui/v1/
I'm also curious if there was documentation that guided you to use https://host:7556/ because this is the #1 most common issue people run into in Zowe v2 and I have to answer roughly 1 ticket per week about it, so I'd like to do better somehow.

**Comment by rayhand1** [comment]
Looking at my notes, i could not find easily how to access ZOWE so I did a TSO NETSTAT SOCK and pointed my browser at each of the ports opened.
It looks better now that i use the correct url.

**Comment by rayhand1** [comment]
Thanks for all the help.  I'll document some more issues tomorrow.

**Comment by rayhand1** [comment]
After using the correct url to get to the desktop I tried each application i found and here is a status:

tn3270 works

vt terminal works

jes explorer gets first screen then just clocks waiting for what?

editor An unknown error occurred: undefined

ip explorer gives first screen, no active connections, no reserved ports
		fill in tcpip jobname at bottom left and still no connections/ports

MVS Explorer Fetch Dataset failed		

USS explorer Fetch children failed

**Comment by 1000TurquoisePogs** [comment]
It looks like you have zosmf commented out in your config.
MVS, USS, and JES explorers depend on zosmf.
IP explorer & editor depend upon ZSS. Now that you fixed one ZSS error, please show us the latest logs, there must be another error.

**Comment by rayhand1** [comment]
[ZWE.APP.LOG.TXT](https://github.com/zowe/zss/files/10077244/ZWE.APP.LOG.TXT)
[ZWE.ZSS.LOG.TXT](https://github.com/zowe/zss/files/10077245/ZWE.ZSS.LOG.TXT)
[ZWESLSTC.OUTPUT.TXT](https://github.com/zowe/zss/files/10077246/ZWESLSTC.OUTPUT.TXT)
here are the latest logs

**Comment by Martin-Zeithaml** [comment]
Seems to be same as #523

**Comment by rayhand1** [comment]
The S0C4 problem was solved yesterday by changing
zss:
tls: false
to
tls: true

**Comment by rayhand1** [comment]
turned on zosmf in yaml.conf

jes explorer works
editor works
ip explorer works
vt terminal works

mvs explorer no datasets found (fetch datasets failed)

following zowe desktop command
zowe zos-files list data-set "zzg047.*" --host plp321.sys.eds.com --port 9445 --user zzg047
I get the following error;
Command Error:
z/OSMF REST API Error:
http(s) request error event called
Error: certificate has expired

do you have instructions to correct this?

Thanks
Ray

**Comment by rayhand1** [comment]
I added -reject-unauthorized false and now my cli command works

**Comment by rayhand1** [comment]
we can close this.
Thanks everyone for all the great help.

**Comment by rayhand1** [comment]
It was a real pleasure working with you folks.
