### ISSUE TITLE
Question: How to update a dataset with ZSS when open in ISPF browse

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zss#562]
A question came in that I need help with so posting it here:

> I was using dataset APIs of ZSS and could notice that update dataset request failed and returns ‘busy response’ if DSN is in browse mode at ISPF or DSN is allocated in started task DD(enqueue DISP=SHR) and zss dataset API do not allow to update. On the other hand we could see for same scenario ZOSMF dataset api allow to update DSN.Any one could please help me to understand above stated behaviour of zss or do we have any header which we can include for above operation to succeed.

It involves the function https://github.com/zowe/zss/blob/298ea08b0a8b7bc759e49ee696d7b14736a92e8e/c/datasetjson.c#L903.

They also asked:

> I am also looking for API or way to execute console command in mainframe using zss. 

I don't think it exists currently but did we have a prototype of this ever?

**Comment by 1000TurquoisePogs** [comment]
We raised questions for investigation including:

some editors hold exclusive locks and some dont, and on certain conditions. what does ispf do?
do we use the same locks as ispf to be a good citizen to ispf?
why doesnt this happen to zosmf?

Lets check a tool like SDSF to see which locks are held, when?



~can you edit when someone elses read, while both are in ispf?~
* yes.

could it have been that there was someone in ispf edit instead?

**Comment by hosathota** [comment]
Hi, 
 is there any update on this? We are in the process of building set of APIs and this is a critical API support. Any update is appreciated.

Thanks and regards
Vishwa

**Comment by hosathota** [comment]
Can this issue be looked into in near future?
