### ISSUE TITLE
High Availability mode session cookie name

### ISSUE THREAD

**Issue by pablocarle** [zowe/zss#599]
**Describe the bug**

Linked to https://github.com/zowe/zlux/issues/969

The function to resolve the session cookie name uses environment variables that are not available in Zowe V2 installer.
https://github.com/zowe/zss/blob/d0db646c0b579e43bdaddeda8ef4d854a86139df/c/zss.c#L1097
`ZOWE_INSTANCE` and `ZWE_HA_INSTANCES_COUNT`

This can result in errors in session refresh feature of zlux when started in HA mode.

**Steps to Reproduce**

1. Open Zowe Desktop in an HA-enabled Zowe instance

**Expected behavior**

`jedHTTPSession` should either take values of `jedHTTPSession.<port>` or `jedHTTPSession.<instance id>` depending on the Zowe mode.

**Describe your environment**

- Zowe version number (Check the Desktop login screen, or manifest.json in the Zowe install folder): nightly v2
- Install method (pax, smpe, kubernetes, github clone): pax
- Operating system (z/OS, kubernetes, etc) and OS version: z/OS

**Comment by 1000TurquoisePogs** [comment]
This was merged for v2.15.0
