### ISSUE TITLE
Client certificates as an authentication method

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zss#631]
Allow ZSS to accept client certificates as an authentication method.
Not only useful, but fixes a problem in Zowe in which client certificate use with APIML currently involves a chicken-and-egg handshake to ZSS that is undesirable to STC configuration.

**Comment by jordanfilteau1995** [comment]
@1000TurquoisePogs Can we close this for housekeeping? Reopen if an issue.
