### ISSUE TITLE
z/OS 3.1 CEE3204S Error 

### ISSUE THREAD

**Issue by struga0258** [zowe/zss#651]
When running Zowe on z/OS 3.1 I keep encountering the following error during startup: 

```
CEE3204S The system detected a protection exception (System Completion Code=0C4).
         From entry point main at compile unit offset +00003E38 at entry offset +00003E38 at address 1480FC98.
```

**Comment by JoeNemo** [comment]
Please add more info.  System Log, CEEDUMP's, etc.

**Comment by struga0258** [comment]
[CEEDUMP.20230927.094916.33620129.txt](https://github.com/zowe/zss/files/12974319/CEEDUMP.20230927.094916.33620129.txt)
[CEEDUMP.20230927.095324.33620036.txt](https://github.com/zowe/zss/files/12974329/CEEDUMP.20230927.095324.33620036.txt)

**Comment by struga0258** [comment]
I have attached two CEEDUMPS

**Comment by JoeNemo** [comment]
@hogstrom is this the right bug?   Can you post ZSS log and system log if anything looks interesting there

**Comment by hogstrom** [comment]
@JoeNemo Yes, this is the bug.  As noted, the dumps do not really provide a smoking gun.

@struga0258 Can you provide the job log for this error.  The dump doesn't really provide enough information.

It would be helpful to outline the steps used to recreate this so that we can duplicate on an internal system.

**Comment by hogstrom** [comment]
I've recreated the issue on a system.  LE is blocking diagnostic data using a SPIE.  Attempting another recreate with the following options 

ENVAR("LIBPATH=/usr/lib")
CEEDUMP(60,SYSOUT=*,FREE=END,SPIN=UNALLOC)
DYNDUMP(*USERID,NODYNAMIC,NOTDUMP)
TERMTHDACT(DUMP,,256)
TRACE(ON,16K,NODUMP,LE=1)
TRAP(ON,NOSPIE)

**Comment by hogstrom** [comment]
UPDATE: 

The root problem is the command `/bin/ipcs`.    

When attempting this command from the command line the same abend occurs outside of Zowe.  This is an IBM defect.  I'm opening a PMR with IBM for the issue.

```
$ /bin/ipcs -a

IPC status as of Thu Nov  9 09:21:33 2023
 B ]
res:
s  %10.1d s         d        0      LSPID      LRPID
GROUP CGROUP   QNUM QBYTES  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
GROUP CGROUP   QNUM QBYTES�  CTIME          0          0
ues:
res:
s CEE3204S The system detected a protection exception (System Completion Code=0C4).
         From entry point main at compile unit offset +00003E38 at entry offset +00003E38 at address 20B0F228.
 %10.1d [1] + Done(139) /bin/ipcs -a
  50399702	Segmentation violation	/bin/ipcs
```

Since Zowe is impacted by this IBM issue I'm going to close this issue.

**Comment by hogstrom** [comment]
Here is the IBM PTF that addresses the issue in /bin/ipcs that needs to be applied to avoid the S0C4.

PTF UJ93511 (APAR OA65028)
