### ISSUE TITLE
Zowe Editor  An unknown error occured: undefined

### ISSUE THREAD

**Issue by rorrss** [zowe/zss#695]
**Describe the bug**
Zowe Editor Is not working correctly 

**Steps to Reproduce**

1.When opening editor in zowe
2. reciving message :An unknown error occured: undefined

**Expected behavior**
Editor should work correctly without issue

**Screenshots**
![image](https://github.com/zowe/community/assets/163416231/25171994-f867-472d-b55f-696eefc9a1b5)

**Logs**
![image](https://github.com/zowe/community/assets/163416231/69bda661-deac-4cbb-b75e-0510cf7e2639)

**Details**
In zweslstc reciving abend issue 0C4-11

**Web Browser Details (if the bug relates to Zowe Desktop usage):**
All browsers

**Additional context**
Hello. I would like to ask you if anyone faced this issue before. I compared settings from other customers where installation of mine went fine and last installation have this issue. Please let me know. Thank you

**Comment by 1000TurquoisePogs** [comment]
This may be an issue already fixed, not sure. I've certainly seen that error before but it could have different causes.
What version of Zowe are you on?
What datasets are you trying to look at when you get the OC4-11?

In your browser, if you hit f12, you can get the developer tools console. In the network tab, you can see which requests were issues. There's probably an error 500 associated with the failed request, and if you can find which one, it may help us know which request failed.
For example, is it a very large PDS? Or a dataset with unusual symbols?

**Comment by rorrss** [comment]
@1000TurquoisePogs  Hello
It actually does not matter what im trying to open by Editor.
![image](https://github.com/zowe/zss/assets/163416231/d8757895-4769-48ff-bc41-934c1f64b61d)

It shows same issue all the time. As you can see USS has same issue.

I am using zowe 2.14.0, but had this issue in 2.13 too

here is a network log:
![image](https://github.com/zowe/zss/assets/163416231/40fe43ed-3f94-42f1-afd9-5369984b935a)

Thank you for checking

**Comment by JoeNemo** [comment]
There is most likely a logrec entry for the captured OC4-04 in the zss server address-space.     If this yields no info we may need a SLIP trap on OC4 for the zss address space.   

I assume the ZSS server successfully handled a user authentication request, so it probably got some internal error after that.   Is the whole server log available?   

Also, was an SVCDUMP taken for this failure?

**Comment by JoeNemo** [comment]
Maybe someday Zowe can have a config option for not pushing a recovery context in httpserver.c when handling a service request and let errors generate dumps and halt the server (just for debugging purposes).

**Comment by rorrss** [comment]
Hello. very sorry for a delay. I had vacation last week.

So here is what i did:
I made Sliptrap for  0c4

slip set,id=ROM1,j=ZWESLSTC,c=0c4,a=svcd,end

this was not working, becouse when error occurs STC still running.

I made logrec report if is it helpful to you: 

[LOGREC.txt](https://github.com/zowe/zss/files/14918057/LOGREC.txt)
[LOGREC.log](https://github.com/zowe/zss/files/14918065/LOGREC.log)

Issue still remain the same. 
Please let me know if you need anything else

Thank you very much

**Comment by ifakhrutdinov** [comment]
> this was not working, becouse when error occurs STC still running.

An SVC dump can be taken when the STC is running. In the SYSLOG, do you see any corresponding messages about the reasons a dump was not taken?

**Comment by rorrss** [comment]
Hello Guys, an SVC Dump has been taken
The limit for uploading a file here is 25MB. SVC DUMP is 375MB. Where do you want to upload it?

**Comment by rorrss** [comment]
[https://kyndrylde-my.sharepoint.com/:u:/r/personal/roman_horak1_kyndryl_com/Documents/Shared%20to%20internet/[ZOWE.DUMP.TRS](https://kyndrylde-my.sharepoint.com/:u:/r/personal/roman_horak1_kyndryl_com/Documents/Shared%20to%20internet/ZOWE.DUMP.TRS?csf=1&web=1&e=YhgxOJ)?csf=1&web=1&e=YhgxOJ](ZOWE SVC Dump)

**Comment by rorrss** [comment]
[Zowe SVC DUMP](https://kyndrylde-my.sharepoint.com/:u:/r/personal/roman_horak1_kyndryl_com/Documents/Shared%20to%20internet/[ZOWE.DUMP.TRS](https://kyndrylde-my.sharepoint.com/:u:/r/personal/roman_horak1_kyndryl_com/Documents/Shared%20to%20internet/ZOWE.DUMP.TRS?csf=1&web=1&e=YhgxOJ)?csf=1&web=1&e=YhgxOJ)

please check and let me know

**Comment by JoeNemo** [comment]
Can you upload it to GitHub?   If there are security questions, let's discuss?

**Comment by rorrss** [comment]
Hello Guys. This issue has been fixed.

For an information it was an issue in hour Language Enviroment.

gsk_def_malloc
SSL could not allocate memory

We changed Parameters in CEEPRM member from 
NOSIMVRD
STACK(128K,128K,BELOW,KEEP,4K,4096),
to
STACK(128K,128K,BELOW,KEEP,512K,128K)

And after zowe restart it start to run. Thank you very much for your attention.

**Comment by 1000TurquoisePogs** [comment]
Oh, okay thank you, we should document or enforce this!

**Comment by LukeG-96** [comment]
Hello. I recently installed Zowe v2.17 and I'm also getting this error. It looks as though the endpoint for mine can't be found? I'm not sure what I need to do to resolve this, but any help would be appreciated.
![Snag_55b335](https://github.com/user-attachments/assets/70217f7c-85a9-4120-b46d-beeba5219268)
