### ISSUE TITLE
Parmlib ZWESIP00: required prefix not validated by schema

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zss#705]
Make the handling of ZIS PARMLIB member less confusing for new users:
* `zowe.setup.dataset.parmlibMembers.zis`
  * It is schema validated as member name, but in fact, [prefix `ZWESIP` is required and 2 chars must follow](https://github.com/zowe/zss/blob/180114f52ccbc56b42720cdab1290769b3626c94/c/zis/server.c#L62-L65)
  * You can set it to `MYPARM12` and it will be validated as ok
* When started, STC will try to search for [default](https://github.com/zowe/zss/blob/180114f52ccbc56b42720cdab1290769b3626c94/samplib/zis/ZWESIS01#L1) `ZWESIP00`

We should allow to change only what can be changed.
We have to use such change to provide working STC.

For example:
* `zowe.setup.dataset.parmlibMembers.zisSuffix` - required length = 2
* `//ZWESIS01  PROC NAME='ZWESIS_STD',MEM={zowe.setup.dataset.parmlibMembers.zisSuffix},RGN=0M`

**Comment by JoeNemo** [comment]
A pattern validation for YAML, or something similar, needs to be added to the JSON schema

**Comment by Martin-Zeithaml** [comment]
### Schema validation
Part of [3718](https://github.com/zowe/zowe-install-packaging/commit/cf70fe4995b9922fee441e1ff0ef16758a6ad5aa).

### Templating
#### `ZWEIMVS`
For testing purposes, `ZWE_` and `zowe.` used.
```
//SYSIN DD *
  COPY OUTDD=SYSUT2,INDD=SYSUT1
  SELECT MEMBER=((ZWESIP00,{ZWE_zowe_setup_dataset_parmlibMembers_zis},R))
  SELECT MEMBER=((ZWESIP00,{zowe.setup.dataset.parmlibMembers.zis},R))
//*
```
If the `zis` not set, it will return:
```
//SYSIN DD *
  COPY OUTDD=SYSUT2,INDD=SYSUT1
  SELECT MEMBER=((ZWESIP00,CFG.ZWE_ZOWE_SETUP_DATASET_PARMLIBMEMBERS_ZIS,R))
  SELECT MEMBER=((ZWESIP00,CFG.ZOWE.SETUP.DATASET.PARMLIBMEMBERS.ZIS,R))
//*
```
#### `ZWESISTC`
How to set just suffix via JCL templating?
`//ZWESIS01  PROC NAME='ZWESIS_STD',MEM=00,RGN=0M`

**Comment by JoeNemo** [comment]
@jordanfilteau1995 Are you willing to take an enhancement request to support some string manipluation in the templating logic?

**Comment by Martin-Zeithaml** [comment]
#### `ZWESISTC` update

It is even more complicated, we are supporting customization of the name via `components.zss.crossMemoryServerName`.

We need to have ability to template this with yaml or default values:
```
//ZWESIS01  PROC NAME='{components.zss.crossMemoryServerName or ZWESIS_STD}',
//   MEM={substring of zowe.setup.dataset.parmlibMembers.zis or 00},RGN=0M
```

**Comment by JoeNemo** [comment]
@1000TurquoisePogs will be adding this to defaults and this will probably close the issue.

**Comment by JoeNemo** [comment]
Since this bug is not reported as affecting anyone in the outside world, we can probably do this in the course of V3 work.
