### ISSUE TITLE
ZWESIS01 Status check should not use a simulated login

### ISSUE THREAD

**Issue by hogstrom** [zowe/zss#8]
On my system I receive the following message:

> ICH408I USER(D U MM Y) GROUP(        ) NAME(???                 ) 411 
>   LOGON/JOB INITIATION - USER AT TERMINAL          NOT RACF-DEFINED   
> 
It appears that on line 670 of c/zss.c a faux logon is attempted using a defunct userID called "D U MM Y".  This generates a log message and a RACF audit of a filed logon attempt.  

To avoid that issue, I suggest that we pass a ZWEIST67 (perhaps this is configurable) and when we see that logon in zowe-common-c we do not actually execute the FASTAUTH and simply return.  This should achieve the goal of authorization without creating false audit records.

**Comment by ifakhrutdinov** [comment]
@hogstrom would making a status cross-memory service be a better solution? It could return very basic information about the server and help identify an offline instance or lack of permissions.

**Comment by gadyck** [comment]
Why the dummy request?  It is not good form. If you must issue it and are authorized, you can suppress logging and messages

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ifakhrutdinov** [comment]
@gadyck Yes, that was a very cheap way to do a health check at that state of dev process. Now we need something more robust and specialized. Would a separate service for checking the status of the cross-memory server make sense?

**Comment by hogstrom** [comment]
I'd agree with a service as you both indicated.  Something like zisCheckServerStatus makes sense to me.  Its concise and specific.

**Comment by ifakhrutdinov** [comment]
The following pull-requests have been created:
* [Add a core service that returns status information (zowe-common-c)](https://github.com/zowe/zowe-common-c/pull/14)
* [Use the new cross-memory status service (zss)](https://github.com/zowe/zss/pull/10)

**Comment by 1000TurquoisePogs** [comment]
Closing this one due to merges. Reopen this if whatever version comes after 1.0.1 still has this issue.
